# -*- coding: utf-8 -*-
"""PruebaMiAguila.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i8fkQRHutDPkpuFEYQW_IcFv8ONGKmqS

# Matriz correlación
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

db = pd.read_csv("Train.csv")
db.info()

db.head()

sns.pairplot(db)

correlacion = db.corr()
correlacion